### ISSUE TITLE
"TypeError" beim versuch eine Zip hochzuladen

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/zip_install#1]
Beim versuch das CKEditor Addon via Zip_install zu installieren hab ich folgenden Fehler erhalten:

```
"TypeError" thrown in /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Archive/Member.php on line 74
Argument 5 passed to Alchemy\Zippy\Archive\Member::__construct() must be an instance of DateTime, boolean given, called in /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php on line 126

#0 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Adapter/ZipAdapter.php(126): Alchemy\Zippy\Archive\Member->__construct(Object(Alchemy\Zippy\Adapter\Resource\FileResource), Object(Alchemy\Zippy\Adapter\ZipAdapter), 'ckeditor-master...', '0', false, true)
#1 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Adapter/AbstractAdapter.php(68): Alchemy\Zippy\Adapter\ZipAdapter->doListMembers(Object(Alchemy\Zippy\Adapter\Resource\FileResource))
#2 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Archive/Archive.php(94): Alchemy\Zippy\Adapter\AbstractAdapter->listMembers(Object(Alchemy\Zippy\Adapter\Resource\FileResource))
#3 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/vendor/alchemy/zippy/src/Archive/Archive.php(86): Alchemy\Zippy\Archive\Archive->getMembers()
#4 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/lib/zip_upload.php(43): Alchemy\Zippy\Archive\Archive->getIterator()
#5 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/zip_install/pages/install.packages.zip_upload.php(11): zip_upload::validateAndExtractUpload()
#6 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/packages/package.php(228): include('/Users/joachimd...')
#7 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/install.p...', Array)
#8 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/be/controller.php(420): rex_be_controller::includePath('/Users/joachimd...', Array)
#9 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/addons/install/pages/index.php(11): rex_be_controller::includeCurrentPageSubPath()
#10 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/packages/package.php(228): include('/Users/joachimd...')
#11 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/be/controller.php(456): rex_package->includeFile('pages/index.php', Array)
#12 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/lib/be/controller.php(403): rex_be_controller::includePath('/Users/joachimd...')
#13 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/backend.php(138): rex_be_controller::includeCurrentPage()
#14 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/src/core/boot.php(105): require('/Users/joachimd...')
#15 /Users/joachimdoerr/Workingspace/redaxo_5/redaxo/index.php(9): require('/Users/joachimd...')
#16 {main}
```

REDAXO 5.2.0
PHP 7.0.13 
MySQL 5.6.34

Addon: https://github.com/RexDude/ckeditor

Das Addon wurde von Github als Zip geladen.

**Comment by hirbod** [comment]
Bei mir läuft die Installation problemlos durch... Hast du in PHP fileextension und zlib geladen? (eigentlich sollte die Installation des AddOns ohne auch nicht funktionieren). Dennoch mal PHPINFO anschauen bitte
